version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
